name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '6 18 * * 0'

env:
  SPLUNKBASE_USER: ${{ secrets.SPLUNKBASE_USER }}
  SPLUNKBASE_PASS: ${{ secrets.SPLUNKBASE_PASS }}

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: x64
    
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v3
      with:
        path: "scripts/requirements.txt"

    - name: Run Splunkbase Download of Latest release    
      run: python ./scripts/splunkbase-download.py

    - name: Clean Old TA Folder
      run: rm -rf ./TA-QualysCloudPlatform/

    - name: Untar release to folder and clean up downloaded tar.gz
      run: |-
        tar -xf *.tar.gz
        rm *.tar.gz

    - name: Modify Qualys Detection Populator with enhancements via python
      run: |-
        python ./scripts/modify_detectionpopulator.py

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest pull: ${timestamp}" || exit 0
        git push