name: zip release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  publish:
    
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Get Version
      id: get-version
      run: |
        QUALYS_VERSION=`cat TA-QualysCloudPlatform/default/app.conf | grep version | cut -d '=' -f 2 | xargs`
        echo $QUALYS_VERSION
        echo "QUALYS_VERSION=${QUALYS_VERSION}" >> $GITHUB_ENV
        echo '::set-output name=VERSION::$(echo ${QUALYS_VERSION})'

    - name: Validate Version
      run: |
        echo "Version:  ${{ steps.get-version.outputs.VERSION }}"
        echo "ENV Version: ${{ env.QUALYS_VERSION }}"
      
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: 'TA-QualysCloudPlatform'
        filename: 'TA-QualysCloudPlatform-${{ env.QUALYS_VERSION }}.zip'

    - name: create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "TA-QualysCloudPlatform-${{ env.QUALYS_VERSION }}"
        files: |
          TA-QualysCloudPlatform-${{ env.QUALYS_VERSION }}.zip
